GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFycnkiLCJpYXQiOjE3Nzk4NDI3NzAsImV4cCI6MTc3OTg0Mjc5MH0.UMB-IXD4AV2QLEVvg4bblL5CVoittLACO_ardEt5Rwg

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFycnkiLCJpYXQiOjE3Nzk4NDI2NzF9.BoJRb31uIvt9c633CPh8vG-HGGozOctFy1uuAgE8jsE"
}
###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFycnkiLCJpYXQiOjE3Nzk4NDI2NzF9.BoJRb31uIvt9c633CPh8vG-HGGozOctFy1uuAgE8jsE"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Barry"
}