POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "Alice",
  "email": "alice@example.com",
  "password": "password123"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "identifier": "Barry",
  "password": "password123"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "identifier": "barry@example.com",
  "password": "password123"
}

###

@challengeId = paste_challenge_id_here
@verificationCode = paste_verification_code_here

###

POST http://localhost:4000/login/verify
Content-Type: application/json

{
  "challengeId": "{{challengeId}}",
  "verificationCode": "{{verificationCode}}"
}

###

@accessToken = paste_access_token_here
@refreshToken = paste_refresh_token_here

###

GET http://localhost:3000/posts
Authorization: Bearer {{accessToken}}

###

POST http://localhost:3000/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "My Post from MySQL"
}

###

@postId = paste_post_id_here

DELETE http://localhost:3000/posts/{{postId}}
Authorization: Bearer {{accessToken}}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}
